=== Homyaak/kit-isrpo/laba8/src/main/java/ru/kai/inkrot/laba8/ordersXmlSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="order">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="agreements"/>
        <xs:element maxOccurs="unbounded" ref="direction"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="agreements">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="agreement"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="agreement">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="date"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="date" type="xs:NMTOKEN"/>
  <xs:element name="direction">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="groups"/>
      </xs:sequence>
      <xs:attribute name="code" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="groups">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="group"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="student"/>
      </xs:sequence>
      <xs:attribute name="number" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="number"/>
        <xs:element ref="name"/>
        <xs:element ref="type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="number" type="xs:string"/>
  <xs:element name="type" type="xs:integer"/>
  <xs:element name="name" type="xs:string"/>
</xs:schema>

=== Homyaak/kit-isrpo/laba8/src/main/java/ru/kai/inkrot/laba8/ordersXMLDocument.xml
<?xml version="1.0"?>
<order xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='ordersXmlSchema.xsd'>
  <agreements>
    <agreement>
        <name>Иванов Петр Васильевич</name>
        <date>24.08.2019</date>
    </agreement>
    <agreement>
        <name>Петров Николай Ректорович</name>
        <date>25.08.2019</date>
    </agreement>
    <agreement>
        <name>Смирнов Андрей Директорович</name>
        <date>24.08.2019</date>
    </agreement>
  </agreements>
  
  <direction 
        code="09.02.03"
        name="Программирование в компьютерных системах стандарт">
        <groups>
            <group number="4441">
                <student>
                    <number>1</number>
                    <name>Имя Фамилия Отчество</name>
                    <type>1</type>
                </student>
                <student>
                    <number>2</number>
                    <name>Имя Фамилия Отчество</name>
                    <type>1</type>
                </student>
                <student>
                    <number></number>
                    <name>Имя Фамилия Отчество</name>
                    <type>2</type>
                </student>
            </group>
        </groups>
    </direction>
    
    <direction 
        code="09.02.02"
        name="Компьютерные сети">
        <groups>
            <group number="4436">
                <student>
                    <number>1</number>
                    <name>Имя Фамилия Отчество</name>
                    <type>2</type>
                </student>
                <student>
                    <number>2</number>
                    <name>Имя Фамилия Отчество</name>
                    <type>2</type>
                </student>
                <student>
                    <number></number>
                    <name>Имя Фамилия Отчество</name>
                    <type>2</type>
                </student>
            </group>
        </groups>
    </direction>
</order>
